### PR TITLE
Translation.jsjava.prototype

### PR DESCRIPTION
**Pull request by bosticc**
added dependency for pom.xml file, added script.js function and java servlet

### CODE REVIEW

**Comment by bosticc** [comment]
ok still getting merge conflicts, gonna see if i can fix them

**Comment by jdstriker731** [comment]
Okay, Will wait for you too fix them then

**Comment by bosticc** [comment]
ok yeah i think i understand why. on the first pull request I had, for some reason one of the target files got modified, so I added them, now every time I try to make a pr i get merge conflicts and it seems like they're too big to modify in github :/

**Comment by jdstriker731** [comment]
Maybe going forward to prevent this, lets just make sure our target folders are empty lol. 
How should we fix this now?

**Comment by bosticc** [comment]
man im not even sure!! i really don't even understand the target files in the first place

**Comment by jdstriker731** [comment]
I think it might be due to us having slightly different versions of the project being built, so our contents within our individual target folders are going to be empty.

**Comment by jdstriker731** [comment]
I'm gonna try manually deleting the target folders from GitHub, then you can send this PR (for the third time). Just make sure to run "mvn clean" before you push to github, so that the target folder is empty

**Comment by bosticc** [comment]
john wait!!! we fixed it i just got off a call with cam

**Comment by bosticc** [comment]
closing this branch, merge conflicts have been avoided

**Pull request closed without merging**
